version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: student_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin123!
      MYSQL_DATABASE: student
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  db_data:
